spring.cloud.stream:
   function:
      definition: sedatCode
   bindings:
      domainProcessor-in-0:
         destination: myfleet_user_error_log
      domainProcessor-out-0:
         destination: myfleet_sedat001_error_log
   kafka:
      bindings:
         domainProcessor-in-0:
            consumer:
               configuration:
                  value:
                     deserializer: org.apache.kafka.common.serialization.StringSerializer
         domainProcessor-out-0:
            producer:
               configuration:
                  value:
                     serializer: org.apache.kafka.common.serialization.StringSerializer
      binder:
         brokers:
         - 192.168.1.7:9092
         - 192.168.1.8:9092
         